### PR TITLE
Buxfixes

### LINKED ISSUE #14: XGlowExample: Wrong /glow disable message
After using "/glow enable" and "/glow disable" i've got the same messages:
`The test entity is now glowing for all viewers of the glow object.`

### PR DESCRIPTION
**Pull request by Dymeth**
Fixed #14 and #15

### CODE REVIEW

File: api/src/main/java/ru/xezard/glow/data/glow/Glow.java [hunk 1]
```diff
@@ -66,7 +66,7 @@ private AbstractPacket createGlowPacket(Entity entity, boolean glow)
 
         entityMetadata.setEntityID(entity.getEntityId());
 
-        WrappedDataWatcher dataWatcher = WrappedDataWatcher.getEntityWatcher(entity);
+        WrappedDataWatcher dataWatcher = WrappedDataWatcher.getEntityWatcher(entity).deepClone();
```
Comment (Dymeth) [inline api/src/main/java/ru/xezard/glow/data/glow/Glow.java:69]: Not sure if `deepClone()` should be used instead of `clone()` in this case
